CONFIG_ZMK_KEYBOARD_NAME="Aug1st"
CONFIG_ZMK_USB=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Bật Display & OLED
CONFIG_ZMK_DISPLAY=y
# Kích hoạt giao diện tối ưu từ module zmk-nice-oled
CONFIG_NICE_OLED=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_I2C=y
CONFIG_SSD1306=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
# Cấu hình bắt buộc cho màn hình đơn sắc LVGL trên ZMK
CONFIG_LV_Z_BITS_PER_PIXEL=1
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
