CONFIG_ZMK_KEYBOARD_NAME="Aug1st"
CONFIG_ZMK_USB=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

/* Bật Display & OLED */
CONFIG_ZMK_DISPLAY=y
CONFIG_I2C=y
CONFIG_SSD1306=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
