manifest:
  self:
    path: config
  projects:
    - name: zmk-oled-brightness
      remote: mctechnology17
      url: https://github.com/mctechnology17/zmk-oled-brightness
      revision: main
  remotes:
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
